name = "MPSXD"
uuid = "2dcbb0ad-964e-4844-bb06-146bff5b1d26"
authors = ["PhysicsCodesLab"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TensorXD = "87026d58-cfa7-4eb9-a354-f095ff43cb87"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
